### ISSUE TITLE
Indicators don't display until you tap down button

### ISSUE THREAD

**Issue by DamianMehers** [pebble-examples/content-indicator-demo#2] opened 2015-11-28 11:35 UTC
I noticed that you need to tap the down button for the content indicator to display in this example.  Is this by design?

The solution is to move the creation and setting of the content indicators up in the code, prior to the creation and addition of the text layer.

I'm happy to put together a pull request, but wanted to be sure that it wasn't intended to be this way.

**Comment by C-D-Lewis** [comment] 2015-11-29 04:52
This is by design, but the design changed since the app was written. I will update it.

**Comment by C-D-Lewis** [comment] 2015-11-30 23:37
@DamianMehers Would you like to contribute and make a PR for this? Or shall I handle it?

**Comment by DamianMehers** [comment] 2015-12-01 19:00
@C-D-Lewis It is just a case of moving a chunk of code a few lines up, but I'm happy to submit a PR if it will help.

**Comment by C-D-Lewis** [comment] 2015-12-01 19:02
@DamianMehers It is indeed. If you'd like to be listed as a contributor to this example for 'fame and glory', go right ahead. If not, I can get to this in due time.

**Comment by DamianMehers** [comment] 2015-12-01 19:08
Can't get enough fame and glory :-)  PR created.

**Comment by C-D-Lewis** [comment] 2015-12-01 19:10
Fixed by #3

**Closed as completed** 2015-12-01 19:10 UTC
